# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oz/svn/kdevplatform

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oz/svn/kdevplatform

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Devel\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	cd /home/oz/svn/kdevplatform && $(CMAKE_COMMAND) -E cmake_progress_start /home/oz/svn/kdevplatform/CMakeFiles /home/oz/svn/kdevplatform/plugins/grepview/CMakeFiles/progress.marks
	cd /home/oz/svn/kdevplatform && $(MAKE) -f CMakeFiles/Makefile2 plugins/grepview/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oz/svn/kdevplatform/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f CMakeFiles/Makefile2 plugins/grepview/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/oz/svn/kdevplatform && $(MAKE) -f CMakeFiles/Makefile2 plugins/grepview/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f CMakeFiles/Makefile2 plugins/grepview/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/oz/svn/kdevplatform && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
plugins/grepview/CMakeFiles/kdevgrepview.dir/rule:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f CMakeFiles/Makefile2 plugins/grepview/CMakeFiles/kdevgrepview.dir/rule
.PHONY : plugins/grepview/CMakeFiles/kdevgrepview.dir/rule

# Convenience name for target.
kdevgrepview: plugins/grepview/CMakeFiles/kdevgrepview.dir/rule
.PHONY : kdevgrepview

# fast build rule for target.
kdevgrepview/fast:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/build
.PHONY : kdevgrepview/fast

# Convenience name for target.
plugins/grepview/CMakeFiles/kdevgrepview_automoc.dir/rule:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f CMakeFiles/Makefile2 plugins/grepview/CMakeFiles/kdevgrepview_automoc.dir/rule
.PHONY : plugins/grepview/CMakeFiles/kdevgrepview_automoc.dir/rule

# Convenience name for target.
kdevgrepview_automoc: plugins/grepview/CMakeFiles/kdevgrepview_automoc.dir/rule
.PHONY : kdevgrepview_automoc

# fast build rule for target.
kdevgrepview_automoc/fast:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview_automoc.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview_automoc.dir/build
.PHONY : kdevgrepview_automoc/fast

# target to build an object file
grepdialog.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepdialog.o
.PHONY : grepdialog.o

# target to preprocess a source file
grepdialog.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepdialog.i
.PHONY : grepdialog.i

# target to generate assembly for a file
grepdialog.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepdialog.s
.PHONY : grepdialog.s

# target to build an object file
grepfindthread.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepfindthread.o
.PHONY : grepfindthread.o

# target to preprocess a source file
grepfindthread.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepfindthread.i
.PHONY : grepfindthread.i

# target to generate assembly for a file
grepfindthread.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepfindthread.s
.PHONY : grepfindthread.s

# target to build an object file
grepjob.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepjob.o
.PHONY : grepjob.o

# target to preprocess a source file
grepjob.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepjob.i
.PHONY : grepjob.i

# target to generate assembly for a file
grepjob.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepjob.s
.PHONY : grepjob.s

# target to build an object file
grepoutputdelegate.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputdelegate.o
.PHONY : grepoutputdelegate.o

# target to preprocess a source file
grepoutputdelegate.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputdelegate.i
.PHONY : grepoutputdelegate.i

# target to generate assembly for a file
grepoutputdelegate.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputdelegate.s
.PHONY : grepoutputdelegate.s

# target to build an object file
grepoutputmodel.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputmodel.o
.PHONY : grepoutputmodel.o

# target to preprocess a source file
grepoutputmodel.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputmodel.i
.PHONY : grepoutputmodel.i

# target to generate assembly for a file
grepoutputmodel.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputmodel.s
.PHONY : grepoutputmodel.s

# target to build an object file
grepoutputview.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputview.o
.PHONY : grepoutputview.o

# target to preprocess a source file
grepoutputview.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputview.i
.PHONY : grepoutputview.i

# target to generate assembly for a file
grepoutputview.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepoutputview.s
.PHONY : grepoutputview.s

# target to build an object file
greputil.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/greputil.o
.PHONY : greputil.o

# target to preprocess a source file
greputil.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/greputil.i
.PHONY : greputil.i

# target to generate assembly for a file
greputil.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/greputil.s
.PHONY : greputil.s

# target to build an object file
grepviewplugin.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepviewplugin.o
.PHONY : grepviewplugin.o

# target to preprocess a source file
grepviewplugin.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepviewplugin.i
.PHONY : grepviewplugin.i

# target to generate assembly for a file
grepviewplugin.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/grepviewplugin.s
.PHONY : grepviewplugin.s

# target to build an object file
kdevgrepview_automoc.o:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/kdevgrepview_automoc.o
.PHONY : kdevgrepview_automoc.o

# target to preprocess a source file
kdevgrepview_automoc.i:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/kdevgrepview_automoc.i
.PHONY : kdevgrepview_automoc.i

# target to generate assembly for a file
kdevgrepview_automoc.s:
	cd /home/oz/svn/kdevplatform && $(MAKE) -f plugins/grepview/CMakeFiles/kdevgrepview.dir/build.make plugins/grepview/CMakeFiles/kdevgrepview.dir/kdevgrepview_automoc.s
.PHONY : kdevgrepview_automoc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... kdevgrepview"
	@echo "... kdevgrepview_automoc"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... grepdialog.o"
	@echo "... grepdialog.i"
	@echo "... grepdialog.s"
	@echo "... grepfindthread.o"
	@echo "... grepfindthread.i"
	@echo "... grepfindthread.s"
	@echo "... grepjob.o"
	@echo "... grepjob.i"
	@echo "... grepjob.s"
	@echo "... grepoutputdelegate.o"
	@echo "... grepoutputdelegate.i"
	@echo "... grepoutputdelegate.s"
	@echo "... grepoutputmodel.o"
	@echo "... grepoutputmodel.i"
	@echo "... grepoutputmodel.s"
	@echo "... grepoutputview.o"
	@echo "... grepoutputview.i"
	@echo "... grepoutputview.s"
	@echo "... greputil.o"
	@echo "... greputil.i"
	@echo "... greputil.s"
	@echo "... grepviewplugin.o"
	@echo "... grepviewplugin.i"
	@echo "... grepviewplugin.s"
	@echo "... kdevgrepview_automoc.o"
	@echo "... kdevgrepview_automoc.i"
	@echo "... kdevgrepview_automoc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/oz/svn/kdevplatform && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

